import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'ml' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app_name": "RoadGuard India",
    "subtitle": "Public Infrastructure Audit",
    "system_active": "System Active",
    "activity_log": "Activity Log",
    "official_portal": "Official Audit Portal",
    "hero_title_1": "Smart Infrastructure",
    "hero_title_2": "Monitoring System",
    "hero_desc": "Leveraging AI for rapid detection of road hazards and seamless reporting to municipal authorities.",
    "upload_title": "Upload Site Photography",
    "drop_title": "Drop to Upload",
    "upload_desc": "Drag and drop field images here, or browse files",
    "browse_files": "browse files",
    "issue_type": "Issue Type",
    "click_drag": "Click & Drag to Highlight Issue",
    "enter_location": "Enter street/area name...",
    "reset": "Reset",
    "analyze": "Analyze",
    "confirm_location": "Confirm Location",
    "inspection_status": "Inspection Status",
    "report_ref": "Report Ref #",
    "tab_overview": "Overview",
    "tab_analysis": "Analysis",
    "tab_action": "Action",
    "issue_identified": "Issue Identified",
    "location_details": "Location Details",
    "view_maps": "View on Google Maps",
    "ai_cross_reference": "AI Cross-Reference",
    "proceed_action": "Proceed to Action",
    "data_insights": "Data Insights",
    "leading_cause": "Leading Cause",
    "time_analysis": "Time Analysis",
    "high_risk_zones": "Known High-Risk Zones",
    "generate_complaint": "Generate Official Complaint",
    "draft_instruction": "Draft a formal letter to the relevant municipal authority.",
    "draft_button": "Draft Letter",
    "drafting": "Drafting...",
    "letter_preview": "Letter Preview",
    "copy_text": "Copy Text",
    "send_complaint": "Send Complaint",
    "processing": "Processing Data",
    "processing_desc": "System is analyzing infrastructure condition and retrieving geospatial context...",
    "select_coordinates": "Select Coordinates",
    "search_address": "Search address...",
    "locating": "Locating...",
    "my_location": "My Location",
    "surveillance": "Surveillance",
    "geo_tagging": "Geo Tagging",
    "evidence_record": "EVIDENCE RECORD",
    "location_coordinates": "Location Coordinates",
    "new_audit": "New Audit",
    "try_again": "Try Again",
    "processing_error": "Processing Error",
    "day": "Day",
    "night": "Night",
    "select_email": "Select Email Client",
    "choose_send_method": "Choose how you want to send this report",
    "use_default_app": "Use Default App",
    "copied": "Copied",
    "report_ready": "Report ready",
    "report_failed": "Report generation failed",
    "unknown_location": "Unknown Location",
    "tour_welcome_title": "Welcome to RoadGuard",
    "tour_welcome_desc": "Your AI-powered assistant for safer Indian roads. Let's take a quick tour to see how it works.",
    "tour_start": "Start Tour",
    "tour_skip": "Skip",
    "tour_next": "Next",
    "tour_finish": "Get Started",
    "tour_lang_title": "Select Language",
    "tour_lang_desc": "You can change your preferred language here at any time.",
    "tour_logs_title": "Activity Logs",
    "tour_logs_desc": "View your past actions, analysis history, and system status logs here.",
    "tour_upload_title": "Upload Evidence",
    "tour_upload_desc": "Start an audit by uploading a photo of the road hazard (potholes, broken lights, etc.) here.",
    "help_tour": "Replay Tour",
    "continue": "Continue",
    "select_language_first": "Select Your Language"
  },
  hi: {
    "app_name": "रोडगार्ड इंडिया",
    "subtitle": "सार्वजनिक बुनियादी ढांचा ऑडिट",
    "system_active": "सिस्टम सक्रिय",
    "activity_log": "गतिविधि लॉग",
    "official_portal": "आधिकारिक ऑडिट पोर्टल",
    "hero_title_1": "स्मार्ट इंफ्रास्ट्रक्चर",
    "hero_title_2": "निगरानी प्रणाली",
    "hero_desc": "सड़क के खतरों का तेजी से पता लगाने और नगरपालिका अधिकारियों को रिपोर्ट करने के लिए एआई का उपयोग।",
    "upload_title": "साइट की तस्वीर अपलोड करें",
    "drop_title": "अपलोड करने के लिए छोड़ें",
    "upload_desc": "तस्वीरें यहाँ खींचें और छोड़ें, या",
    "browse_files": "फाइलें चुनें",
    "issue_type": "समस्या का प्रकार",
    "click_drag": "समस्या को हाइलाइट करने के लिए क्लिक करें और खींचें",
    "enter_location": "सड़क/क्षेत्र का नाम दर्ज करें...",
    "reset": "रीसेट",
    "analyze": "विश्लेषण करें",
    "confirm_location": "स्थान की पुष्टि करें",
    "inspection_status": "निरीक्षण की स्थिति",
    "report_ref": "रिपोर्ट संदर्भ #",
    "tab_overview": "अवलोकन",
    "tab_analysis": "विश्लेषण",
    "tab_action": "कार्रवाई",
    "issue_identified": "पहचानी गई समस्या",
    "location_details": "स्थान का विवरण",
    "view_maps": "गूगल मैप्स पर देखें",
    "ai_cross_reference": "एआई क्रॉस-रेफरेंस",
    "proceed_action": "कार्रवाई के लिए आगे बढ़ें",
    "data_insights": "डेटा अंतर्दृष्टि",
    "leading_cause": "प्रमुख कारण",
    "time_analysis": "समय विश्लेषण",
    "high_risk_zones": "ज्ञात उच्च जोखिम वाले क्षेत्र",
    "generate_complaint": "आधिकारिक शिकायत उत्पन्न करें",
    "draft_instruction": "संबंधित नगरपालिका प्राधिकारी को एक औपचारिक पत्र तैयार करें।",
    "draft_button": "पत्र तैयार करें",
    "drafting": "मसौदा तैयार हो रहा है...",
    "letter_preview": "पत्र पूर्वावलोकन",
    "copy_text": "टेक्स्ट कॉपी करें",
    "send_complaint": "शिकायत भेजें",
    "processing": "डेटा प्रोसेसिंग",
    "processing_desc": "सिस्टम बुनियादी ढांचे की स्थिति का विश्लेषण कर रहा है...",
    "select_coordinates": "निर्देशांक चुनें",
    "search_address": "पता खोजें...",
    "locating": "खोजा जा रहा है...",
    "my_location": "मेरा स्थान",
    "surveillance": "निगरानी",
    "geo_tagging": "जियो टैगिंग",
    "evidence_record": "साक्ष्य रिकॉर्ड",
    "location_coordinates": "स्थान निर्देशांक",
    "new_audit": "नया ऑडिट",
    "try_again": "पुनः प्रयास करें",
    "processing_error": "प्रोसेसिंग त्रुटि",
    "day": "दिन",
    "night": "रात",
    "select_email": "ईमेल क्लाइंट चुनें",
    "choose_send_method": "चुनें कि आप यह रिपोर्ट कैसे भेजना चाहते हैं",
    "use_default_app": "डिफ़ॉल्ट ऐप का उपयोग करें",
    "copied": "कॉपी किया गया",
    "report_ready": "रिपोर्ट तैयार",
    "report_failed": "रिपोर्ट निर्माण विफल",
    "unknown_location": "अज्ञात स्थान",
    "tour_welcome_title": "रोडगार्ड में आपका स्वागत है",
    "tour_welcome_desc": "सुरक्षित भारतीय सड़कों के लिए आपका एआई-संचालित सहायक। आइए देखते हैं यह कैसे काम करता है।",
    "tour_start": "टूर शुरू करें",
    "tour_skip": "छोड़ें",
    "tour_next": "अगला",
    "tour_finish": "शुरू करें",
    "tour_lang_title": "भाषा चुनें",
    "tour_lang_desc": "आप अपनी पसंदीदा भाषा यहाँ कभी भी बदल सकते हैं।",
    "tour_logs_title": "गतिविधि लॉग",
    "tour_logs_desc": "अपने पिछले कार्यों, विश्लेषण इतिहास और सिस्टम स्थिति लॉग को यहाँ देखें।",
    "tour_upload_title": "साक्ष्य अपलोड करें",
    "tour_upload_desc": "सड़क के खतरे (गड्ढे, टूटी लाइटें आदि) की फोटो अपलोड करके ऑडिट शुरू करें।",
    "help_tour": "टूर फिर से देखें",
    "continue": "जारी रखें",
    "select_language_first": "अपनी भाषा चुनें"
  },
  ta: {
    "app_name": "ரோட்கார்ட் இந்தியா",
    "subtitle": "பொது உள்கட்டமைப்பு தணிக்கை",
    "system_active": "அமைப்பு செயலில் உள்ளது",
    "activity_log": "செயல்பாட்டு பதிவு",
    "official_portal": "அதிகாரப்பூர்வ தணிக்கை தளம்",
    "hero_title_1": "ஸ்மார்ட் உள்கட்டமைப்பு",
    "hero_title_2": "கண்காணிப்பு அமைப்பு",
    "hero_desc": "சாலை ஆபத்துகளை விரைவாகக் கண்டறிந்து நகராட்சி அதிகாரிகளுக்கு புகாரளிக்க AI பயன்பாடு.",
    "upload_title": "தள புகைப்படத்தை பதிவேற்றவும்",
    "drop_title": "பதிவேற்ற இங்கே விடவும்",
    "upload_desc": "படங்களை இங்கே இழுத்து விடவும் அல்லது",
    "browse_files": "கோப்புகளைத் தேர்ந்தெடுக்கவும்",
    "issue_type": "சிக்கல் வகை",
    "click_drag": "சிக்கலை முன்னிலைப்படுத்த கிளிக் செய்து இழுக்கவும்",
    "enter_location": "தெரு/பகுதி பெயரை உள்ளிடவும்...",
    "reset": "மீட்டமை",
    "analyze": "பகுப்பாய்வு செய்",
    "confirm_location": "இடத்தை உறுதிப்படுத்தவும்",
    "inspection_status": "ஆய்வு நிலை",
    "report_ref": "அறிக்கை குறிப்பு #",
    "tab_overview": "கண்ணோட்டம்",
    "tab_analysis": "பகுப்பாய்வு",
    "tab_action": "நடவடிக்கை",
    "issue_identified": "கண்டறியப்பட்ட சிக்கல்",
    "location_details": "இடம் விவரங்கள்",
    "view_maps": "கூகிள் மேப்ஸில் காண்க",
    "ai_cross_reference": "AI குறுக்கு குறிப்பு",
    "proceed_action": "நடவடிக்கைக்கு செல்லவும்",
    "data_insights": "தரவு நுண்ணறிவு",
    "leading_cause": "முக்கிய காரணம்",
    "time_analysis": "நேர பகுப்பாய்வு",
    "high_risk_zones": "அதிக ஆபத்துள்ள மண்டலங்கள்",
    "generate_complaint": "அதிகாரப்பூர்வ புகாரை உருவாக்கவும்",
    "draft_instruction": "சம்பந்தப்பட்ட நகராட்சி அதிகாரிகளுக்கு முறையான கடிதத்தை உருவாக்கவும்.",
    "draft_button": "கடிதத்தை உருவாக்கு",
    "drafting": "தயாரிக்கப்படுகிறது...",
    "letter_preview": "கடித முன்னோட்டம்",
    "copy_text": "உரையை நகலெடு",
    "send_complaint": "புகாரை அனுப்பவும்",
    "processing": "தரவு செயலாக்கம்",
    "processing_desc": "அமைப்பு உள்கட்டமைப்பு நிலையை பகுப்பாய்வு செய்கிறது...",
    "select_coordinates": "ஆயங்களைத் தேர்ந்தெடுக்கவும்",
    "search_address": "முகவரியைத் தேடுங்கள்...",
    "locating": "கண்டறியப்படுகிறது...",
    "my_location": "என் இருப்பிடம்",
    "surveillance": "கண்காணிப்பு",
    "geo_tagging": "ஜியோ டேக்கிங்",
    "evidence_record": "ஆதார பதிவு",
    "location_coordinates": "இடம் ஆயங்கள்",
    "new_audit": "புதிய தணிக்கை",
    "try_again": "மீண்டும் முயற்சிக்கவும்",
    "processing_error": "செயலாக்க பிழை",
    "day": "பகல்",
    "night": "இரவு",
    "select_email": "மின்னஞ்சல் செயலியைத் தேர்ந்தெடுக்கவும்",
    "choose_send_method": "இந்த அறிக்கையை எப்படி அனுப்ப விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்",
    "use_default_app": "இயல்புநிலை செயலியைப் பயன்படுத்தவும்",
    "copied": "நகலெடுக்கப்பட்டது",
    "report_ready": "அறிக்கை தயார்",
    "report_failed": "அறிக்கை உருவாக்கம் தோல்வியடைந்தது",
    "unknown_location": "தெரியாத இடம்",
    "tour_welcome_title": "RoadGuard-க்கு வரவேற்கிறோம்",
    "tour_welcome_desc": "பாதுகாப்பான இந்திய சாலைகளுக்கான உங்கள் AI உதவியாளர். இது எவ்வாறு செயல்படுகிறது என்பதைப் பார்க்க ஒரு விரைவான பயணத்தை மேற்கொள்வோம்.",
    "tour_start": "சுற்றுப்பயணத்தைத் தொடங்குங்கள்",
    "tour_skip": "தவிர்",
    "tour_next": "அடுத்து",
    "tour_finish": "தொடங்குங்கள்",
    "tour_lang_title": "மொழியைத் தேர்ந்தெடுக்கவும்",
    "tour_lang_desc": "உங்கள் விருப்பமான மொழியை இங்கே எப்போது வேண்டுமானாலும் மாற்றிக்கொள்ளலாம்.",
    "tour_logs_title": "செயல்பாட்டு பதிவுகள்",
    "tour_logs_desc": "உங்கள் கடந்தகால நடவடிக்கைகள், பகுப்பாய்வு வரலாறு மற்றும் கணினி நிலை பதிவுகளை இங்கே காண்க.",
    "tour_upload_title": "ஆதாரத்தைப் பதிவேற்றவும்",
    "tour_upload_desc": "சாலை ஆபத்தின் (குழிகள், உடைந்த விளக்குகள் போன்றவை) புகைப்படத்தைப் பதிவேற்றுவதன் மூலம் தணிக்கையைத் தொடங்கவும்.",
    "help_tour": "சுற்றுப்பயணத்தை மீண்டும் இயக்கவும்",
    "continue": "தொடரவும்",
    "select_language_first": "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்"
  },
  te: {
    "app_name": "రోడ్‌గార్డ్ ఇండియా",
    "subtitle": "ప్రజా మౌలిక సదుపాయాల ఆడిట్",
    "system_active": "సిస్టమ్ యాక్టివ్",
    "activity_log": "యాక్టివిటీ లాగ్",
    "official_portal": "అధికారిక ఆడిట్ పోర్టల్",
    "hero_title_1": "స్మార్ట్ ఇన్ఫ్రాస్ట్రక్చర్",
    "hero_title_2": "పర్యవేక్షణ వ్యవస్థ",
    "hero_desc": "రహదారి ప్రమాదాలను వేగంగా గుర్తించడం మరియు మునిసిపల్ అధికారులకు నివేదించడం కోసం AIని ఉపయోగించడం.",
    "upload_title": "సైట్ ఫోటో అప్‌లోడ్ చేయండి",
    "drop_title": "అప్‌లోడ్ చేయడానికి ఇక్కడ వదలండి",
    "upload_desc": "ఫోటోలను ఇక్కడ లాగండి లేదా",
    "browse_files": "ఫైళ్లను ఎంచుకోండి",
    "issue_type": "సమస్య రకం",
    "click_drag": "సమస్యను హైలైట్ చేయడానికి క్లిక్ చేసి లాగండి",
    "enter_location": "వీధి/ప్రాంతం పేరు నమోదు చేయండి...",
    "reset": "రీసెట్",
    "analyze": "విశ్లేషించు",
    "confirm_location": "లొకేషన్ నిర్ధారించండి",
    "inspection_status": "తనిఖీ స్థితి",
    "report_ref": "రిపోర్ట్ రిఫరెన్స్ #",
    "tab_overview": "అవలోకనం",
    "tab_analysis": "విశ్లేషణ",
    "tab_action": "చర్య",
    "issue_identified": "గుర్తించిన సమస్య",
    "location_details": "లొకేషన్ వివరాలు",
    "view_maps": "గూగుల్ మ్యాప్స్‌లో చూడండి",
    "ai_cross_reference": "AI క్రాస్-రిఫరెన్స్",
    "proceed_action": "చర్యకు వెళ్లండి",
    "data_insights": "డేటా అంతర్దృష్టులు",
    "leading_cause": "ప్రధాన కారణం",
    "time_analysis": "సమయ విశ్లేషణ",
    "high_risk_zones": "అధిక ప్రమాద ప్రాంతాలు",
    "generate_complaint": "అధికారిక ఫిర్యాదును రూపొందించండి",
    "draft_instruction": "సంబంధిత మునిసిపల్ అధికారికి అధికారిక లేఖను రూపొందించండి.",
    "draft_button": "లేఖను రూపొందించు",
    "drafting": "లేఖ తయారవుతోంది...",
    "letter_preview": "లేఖ ప్రివ్యూ",
    "copy_text": "కాపీ చేయండి",
    "send_complaint": "ఫిర్యాదు పంపండి",
    "processing": "డేటా ప్రాసెసింగ్",
    "processing_desc": "సిస్టమ్ మౌలిక సదుపాయాల స్థితిని విశ్లేషిస్తోంది...",
    "select_coordinates": "కోఆర్డినేట్‌లను ఎంచుకోండి",
    "search_address": "చిరునామా వెతకండి...",
    "locating": "వెతుకుతోంది...",
    "my_location": "నా లొకేషన్",
    "surveillance": "నిఘా",
    "geo_tagging": "జియో ట్యాగింగ్",
    "evidence_record": "సాక్ష్యం రికార్డ్",
    "location_coordinates": "లొకేషన్ కోఆర్డినేట్స్",
    "new_audit": "కొత్త ఆడిట్",
    "try_again": "మళ్ళీ ప్రయత్నించండి",
    "processing_error": "ప్రాసెసింగ్ లోపం",
    "day": "పగలు",
    "night": "రాత్రి",
    "select_email": "ఈమెయిల్ యాప్ ఎంచుకోండి",
    "choose_send_method": "మీరు ఈ నివేదికను ఎలా పంపాలనుకుంటున్నారో ఎంచుకోండి",
    "use_default_app": "డిఫాల్ట్ యాప్ ఉపయోగించండి",
    "copied": "కాపీ చేయబడింది",
    "report_ready": "నివేదిక సిద్ధంగా ఉంది",
    "report_failed": "నివేదిక విఫలమైంది",
    "unknown_location": "తెలియని ప్రదేశం",
    "tour_welcome_title": "RoadGuardకి స్వాగతం",
    "tour_welcome_desc": "సురక్షితమైన భారతీయ రహదారుల కోసం మీ AI-ఆధారిత సహాయకం. ఇది ఎలా పనిచేస్తుందో చూడటానికి శీఘ్ర పర్యటన చేద్దాం.",
    "tour_start": "టూర్ ప్రారంభించండి",
    "tour_skip": "దాటవేయి",
    "tour_next": "తరువాత",
    "tour_finish": "ప్రారంభించండి",
    "tour_lang_title": "భాషను ఎంచుకోండి",
    "tour_lang_desc": "మీరు ఎప్పుడైనా మీ ప్రాధాన్యత భాషను ఇక్కడ మార్చుకోవచ్చు.",
    "tour_logs_title": "కార్యకలాపాల లాగ్‌లు",
    "tour_logs_desc": "మీ గత చర్యలు, విశ్లేషణ చరిత్ర మరియు సిస్టమ్ స్థితి లాగ్‌లను ఇక్కడ వీక్షించండి.",
    "tour_upload_title": "ఆధారాన్ని అప్‌లోడ్ చేయండి",
    "tour_upload_desc": "రహదారి ప్రమాదం (గుంతలు, పగిలిన లైట్లు మొదలైనవి) యొక్క ఫోటోను అప్‌లోడ్ చేయడం ద్వారా ఆడిట్‌ను ప్రారంభించండి.",
    "help_tour": "టూర్ రీప్లే చేయండి",
    "continue": "కొనసాగించు",
    "select_language_first": "మీ భాషను ఎంచుకోండి"
  },
  kn: {
    "app_name": "ರೋಡ್‌ಗಾರ್ಡ್ ಇಂಡಿಯಾ",
    "subtitle": "ಸಾರ್ವಜನಿಕ ಮೂಲಸೌಕರ್ಯ ಆಡಿಟ್",
    "system_active": "ಸಿಸ್ಟಮ್ ಸಕ್ರಿಯವಾಗಿದೆ",
    "activity_log": "ಚಟುವಟಿಕೆ ಲಾಗ್",
    "official_portal": "ಅಧಿಕೃತ ಆಡಿಟ್ ಪೋರ್ಟಲ್",
    "hero_title_1": "ಸ್ಮಾರ್ಟ್ ಮೂಲಸೌಕರ್ಯ",
    "hero_title_2": "ಮೇಲ್ವಿಚಾರಣಾ ವ್ಯವಸ್ಥೆ",
    "hero_desc": "ರಸ್ತೆ ಅಪಾಯಗಳನ್ನು ತ್ವರಿತವಾಗಿ ಪತ್ತೆಹಚ್ಚಲು ಮತ್ತು ಪುರಸಭೆ ಅಧಿಕಾರಿಗಳಿಗೆ ವರದಿ ಮಾಡಲು AI ಬಳಕೆ.",
    "upload_title": "ಸೈಟ್ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "drop_title": "ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಇಲ್ಲಿ ಬಿಡಿ",
    "upload_desc": "ಚಿತ್ರಗಳನ್ನು ಇಲ್ಲಿ ಎಳೆಯಿರಿ ಮತ್ತು ಬಿಡಿ, ಅಥವಾ",
    "browse_files": "ಫೈಲ್‌ಗಳನ್ನು ಆರಿಸಿ",
    "issue_type": "ಸಮಸ್ಯೆಯ ಪ್ರಕಾರ",
    "click_drag": "ಸಮಸ್ಯೆಯನ್ನು ಹೈಲೈಟ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ಎಳೆಯಿರಿ",
    "enter_location": "ರಸ್ತೆ/ಪ್ರದೇಶದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ...",
    "reset": "ಮರುಹೊಂದಿಸಿ",
    "analyze": "ವಿಶ್ಲೇಷಿಸಿ",
    "confirm_location": "ಸ್ಥಳವನ್ನು ಖಚಿತಪಡಿಸಿ",
    "inspection_status": "ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ",
    "report_ref": "ವರದಿ ಉಲ್ಲೇಖ #",
    "tab_overview": "ಅವಲೋಕನ",
    "tab_analysis": "ವಿಶ್ಲೇಷಣೆ",
    "tab_action": "ಕ್ರಮ",
    "issue_identified": "ಗುರುತಿಸಲಾದ ಸಮಸ್ಯೆ",
    "location_details": "ಸ್ಥಳದ ವಿವರಗಳು",
    "view_maps": "ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್‌ನಲ್ಲಿ ವೀಕ್ಷಿಸಿ",
    "ai_cross_reference": "AI ಅಡ್ಡ-ಉಲ್ಲೇಖ",
    "proceed_action": "ಕ್ರಮಕ್ಕೆ ಮುಂದುವರಿಯಿರಿ",
    "data_insights": "ಡೇಟಾ ಒಳನೋಟಗಳು",
    "leading_cause": "ಪ್ರಮುಖ ಕಾರಣ",
    "time_analysis": "ಸಮಯ ವಿಶ್ಲೇಷಣೆ",
    "high_risk_zones": "ಹೆಚ್ಚಿನ ಅಪಾಯದ ವಲಯಗಳು",
    "generate_complaint": "ಅಧಿಕೃತ ದೂರು ರಚಿಸಿ",
    "draft_instruction": "ಸಂಬಂಧಿತ ಪುರಸಭೆ ಅಧಿಕಾರಿಗೆ ಅಧಿಕೃತ ಪತ್ರವನ್ನು ರಚಿಸಿ.",
    "draft_button": "ಪತ್ರವನ್ನು ರಚಿಸಿ",
    "drafting": "ಕರಡು ತಯಾರಿಸಲಾಗುತ್ತಿದೆ...",
    "letter_preview": "ಪತ್ರ ಮುನ್ನೋಟ",
    "copy_text": "ಪಠ್ಯವನ್ನು ನಕಲಿಸಿ",
    "send_complaint": "ದೂರು ಕಳುಹಿಸಿ",
    "processing": "ಡೇಟಾ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ",
    "processing_desc": "ಸಿಸ್ಟಮ್ ಮೂಲಸೌಕರ್ಯದ ಸ್ಥಿತಿಯನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    "select_coordinates": "ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಆರಿಸಿ",
    "search_address": "ವಿಳಾಸ ಹುಡುಕಿ...",
    "locating": "ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    "my_location": "ನನ್ನ ಸ್ಥಳ",
    "surveillance": "ಕಣ್ಗಾವಲು",
    "geo_tagging": "ಜಿಯೋ ಟ್ಯಾಗಿಂಗ್",
    "evidence_record": "ಸಾಕ್ಷ್ಯ ದಾಖಲೆ",
    "location_coordinates": "ಸ್ಥಳ ನಿರ್ದೇಶಾಂಕಗಳು",
    "new_audit": "ಹೊಸ ಆಡಿಟ್",
    "try_again": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    "processing_error": "ಪ್ರಕ್ರಿಯೆ ದೋಷ",
    "day": "ಹಗಲು",
    "night": "ರಾತ್ರಿ",
    "select_email": "ಇಮೇಲ್ ಆಪ್ ಆಯ್ಕೆಮಾಡಿ",
    "choose_send_method": "ಈ ವರದಿಯನ್ನು ನೀವು ಹೇಗೆ ಕಳುಹಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "use_default_app": "ಡೀಫಾಲ್ಟ್ ಆಪ್ ಬಳಸಿ",
    "copied": "ನಕಲಿಸಲಾಗಿದೆ",
    "report_ready": "ವರದಿ ಸಿದ್ಧವಾಗಿದೆ",
    "report_failed": "ವರದಿ ರಚನೆ ವಿಫಲವಾಗಿದೆ",
    "unknown_location": "ಅಪರಿಚಿತ ಸ್ಥಳ",
    "tour_welcome_title": "RoadGuard ಗೆ ಸ್ವಾಗತ",
    "tour_welcome_desc": "ಸುರಕ್ಷಿತ ಭಾರತೀಯ ರಸ್ತೆಗಳಿಗಾಗಿ ನಿಮ್ಮ AI-ಚಾಲಿತ ಸಹಾಯಕ. ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ ಎಂಬುದನ್ನು ನೋಡಲು ತ್ವರಿತ ಪ್ರವಾಸ ಮಾಡೋಣ.",
    "tour_start": "ಪ್ರವಾಸ ಪ್ರಾರಂಭಿಸಿ",
    "tour_skip": "ಬಿಟ್ಟುಬಿಡಿ",
    "tour_next": "ಮುಂದೆ",
    "tour_finish": "ಪ್ರಾರಂಭಿಸಿ",
    "tour_lang_title": "ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    "tour_lang_desc": "ನೀವು ಯಾವಾಗ ಬೇಕಾದರೂ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಇಲ್ಲಿ ಬದಲಾಯಿಸಬಹುದು.",
    "tour_logs_title": "ಚಟುವಟಿಕೆ ಲಾಗ್‌ಗಳು",
    "tour_logs_desc": "ನಿಮ್ಮ ಹಿಂದಿನ ಕಾರ್ಯಗಳು, ವಿಶ್ಲೇಷಣೆ ಇತಿಹಾಸ ಮತ್ತು ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ ಲಾಗ್‌ಗಳನ್ನು ಇಲ್ಲಿ ವೀಕ್ಷಿಸಿ.",
    "tour_upload_title": "ಸಾಕ್ಷ್ಯ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "tour_upload_desc": "ರಸ್ತೆ ಅಪಾಯದ (ಗುಂಡಿಗಳು, ಮುರಿದ ದೀಪಗಳು ಇತ್ಯಾದಿ) ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡುವ ಮೂಲಕ ಆಡಿಟ್ ಪ್ರಾರಂಭಿಸಿ.",
    "help_tour": "ಪ್ರವಾಸವನ್ನು ಮರುಪ್ಲೇ ಮಾಡಿ",
    "continue": "ಮುಂದುವರಿಸಿ",
    "select_language_first": "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ"
  },
  ml: {
    "app_name": "റോഡ്ഗാർഡ് ഇന്ത്യ",
    "subtitle": "പൊതു അടിസ്ഥാന സൗകര്യ ഓഡിറ്റ്",
    "system_active": "സിസ്റ്റം സജീവമാണ്",
    "activity_log": "ആക്റ്റിവിറ്റി ലോഗ്",
    "official_portal": "ഔദ്യോഗിക ഓഡിറ്റ് പോർട്ടൽ",
    "hero_title_1": "സ്മാർട്ട് ഇൻഫ്രാസ്ട്രക്ചർ",
    "hero_title_2": "നിരീക്ഷണ സംവിധാനം",
    "hero_desc": "റോഡ് അപകടങ്ങൾ വേഗത്തിൽ കണ്ടെത്തുന്നതിനും മുനിസിപ്പൽ അധികാരികൾക്ക് റിപ്പോർട്ട് ചെയ്യുന്നതിനും AI ഉപയോഗിക്കുന്നു.",
    "upload_title": "സൈറ്റ് ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    "drop_title": "അപ്‌ലോഡ് ചെയ്യാൻ ഇവിടെ ഇടുക",
    "upload_desc": "ചിത്രങ്ങൾ ഇവിടെ വലിച്ചിടുക, അല്ലെങ്കിൽ",
    "browse_files": "ഫയലുകൾ തിരഞ്ഞെടുക്കുക",
    "issue_type": "പ്രശ്ന തരം",
    "click_drag": "പ്രശ്നം ഹൈലൈറ്റ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്ത് വലിച്ചിടുക",
    "enter_location": "തെരുവ്/സ്ഥലത്തിന്റെ പേര് നൽകുക...",
    "reset": "റീസെറ്റ്",
    "analyze": "വിശകലനം ചെയ്യുക",
    "confirm_location": "സ്ഥലം സ്ഥിരീകരിക്കുക",
    "inspection_status": "പരിശോധന നില",
    "report_ref": "റിപ്പോർട്ട് റഫറൻസ് #",
    "tab_overview": "അവലോകനം",
    "tab_analysis": "വിശകലനം",
    "tab_action": "നടപടി",
    "issue_identified": "കണ്ടെത്തിയ പ്രശ്നം",
    "location_details": "സ്ഥല വിവരങ്ങൾ",
    "view_maps": "ഗൂഗിൾ മാപ്‌സിൽ കാണുക",
    "ai_cross_reference": "AI ക്രോസ്-റഫറൻസ്",
    "proceed_action": "നടപടിയിലേക്ക് പോകുക",
    "data_insights": "ഡാറ്റാ ഇൻസൈറ്റുകൾ",
    "leading_cause": "പ്രധാന കാരണം",
    "time_analysis": "സമയ വിശകലനം",
    "high_risk_zones": "ഉയർന്ന അപകട സാധ്യതയുള്ള മേഖലകൾ",
    "generate_complaint": "ഔദ്യോഗിക പരാതി തയ്യാറാക്കുക",
    "draft_instruction": "ബന്ധപ്പെട്ട മുനിസിപ്പൽ അധികാരിക്ക് ഔദ്യോഗിക കത്ത് തയ്യാറാക്കുക.",
    "draft_button": "കത്ത് തയ്യാറാക്കുക",
    "drafting": "തയ്യാറാക്കുന്നു...",
    "letter_preview": "കത്ത് പ്രിവ്യൂ",
    "copy_text": "ടെക്സ്റ്റ് പകർത്തുക",
    "send_complaint": "പരാതി അയക്കുക",
    "processing": "ഡാറ്റ പ്രോസസ്സിംഗ്",
    "processing_desc": "സിസ്റ്റം അടിസ്ഥാന സൗകര്യങ്ങളുടെ നില വിശകലനം ചെയ്യുന്നു...",
    "select_coordinates": "കോർഡിനേറ്റുകൾ തിരഞ്ഞെടുക്കുക",
    "search_address": "വിലാസം തിരയുക...",
    "locating": "കണ്ടെത്തുന്നു...",
    "my_location": "എന്റെ സ്ഥലം",
    "surveillance": "നിരീക്ഷണം",
    "geo_tagging": "ജിയോ ടാഗിംഗ്",
    "evidence_record": "തെളിവ് റെക്കോർഡ്",
    "location_coordinates": "സ്ഥല കോർഡിനേറ്റുകൾ",
    "new_audit": "പുതിയ ഓഡിറ്റ്",
    "try_again": "വീണ്ടും ശ്രമിക്കുക",
    "processing_error": "പ്രോസസ്സിംഗ് പിശക്",
    "day": "പകൽ",
    "night": "രാത്രി",
    "select_email": "ഇമെയിൽ ആപ്പ് തിരഞ്ഞെടുക്കുക",
    "choose_send_method": "ഈ റിപ്പോർട്ട് എങ്ങനെ അയക്കണമെന്ന് തിരഞ്ഞെടുക്കുക",
    "use_default_app": "ഡിഫോൾട്ട് ആപ്പ് ഉപയോഗിക്കുക",
    "copied": "പകർത്തി",
    "report_ready": "റിപ്പോർട്ട് തയ്യാറാണ്",
    "report_failed": "റിപ്പോർട്ട് നിർമ്മാണം പരാജയപ്പെട്ടു",
    "unknown_location": "അറിയാത്ത സ്ഥലം",
    "tour_welcome_title": "RoadGuard-ലേക്ക് സ്വാഗതം",
    "tour_welcome_desc": "സുരക്ഷിതമായ ഇന്ത്യൻ റോഡുകൾക്കായി നിങ്ങളുടെ AI അസിസ്റ്റന്റ്. ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നുവെന്ന് കാണാൻ ഒരു ദ്രുത ടൂർ നടത്താം.",
    "tour_start": "ടൂർ ആരംഭിക്കുക",
    "tour_skip": "ഒഴിവാക്കുക",
    "tour_next": "അടുത്തത്",
    "tour_finish": "ആരംഭിക്കുക",
    "tour_lang_title": "ഭാഷ തിരഞ്ഞെടുക്കുക",
    "tour_lang_desc": "നിങ്ങൾക്ക് എപ്പോൾ വേണമെങ്കിലും നിങ്ങളുടെ ഇഷ്ട ഭാഷ ഇവിടെ മാറ്റാം.",
    "tour_logs_title": "ആക്റ്റിവിറ്റി ലോഗുകൾ",
    "tour_logs_desc": "നിങ്ങളുടെ മുൻകാല പ്രവർത്തനങ്ങൾ, വിശകലന ചരിത്രം, സിസ്റ്റം സ്റ്റാറ്റസ് ലോഗുകൾ എന്നിവ ഇവിടെ കാണുക.",
    "tour_upload_title": "തെളിവ് അപ്‌ലോഡ് ചെയ്യുക",
    "tour_upload_desc": "റോഡ് അപകടത്തിന്റെ (കുഴികൾ, തകർന്ന ലൈറ്റുകൾ തുടങ്ങിയവ) ഫോട്ടോ അപ്‌ലോഡ് ചെയ്തുകൊണ്ട് ഓഡിറ്റ് ആരംഭിക്കുക.",
    "help_tour": "ടൂർ വീണ്ടും കാണുക",
    "continue": "തുടരുക",
    "select_language_first": "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക"
  },
  mr: {
    "app_name": "रोडगार्ड इंडिया",
    "subtitle": "सार्वजनिक पायाभूत सुविधा ऑडिट",
    "system_active": "सिस्टम सक्रिय",
    "activity_log": "क्रियाकलाप लॉग",
    "official_portal": "अधिकृत ऑडिट पोर्टल",
    "hero_title_1": "स्मार्ट पायाभूत सुविधा",
    "hero_title_2": "निगरानी प्रणाली",
    "hero_desc": "रस्त्यावरील धोके त्वरित शोधण्यासाठी आणि नगरपालिका अधिकाऱ्यांना अहवाल देण्यासाठी एआयचा वापर.",
    "upload_title": "साइट फोटो अपलोड करा",
    "drop_title": "अपलोड करण्यासाठी येथे सोडा",
    "upload_desc": "येथे फोटो ड्रॅग आणि ड्रॉप करा, किंवा",
    "browse_files": "फाईल्स निवडा",
    "issue_type": "समस्येचा प्रकार",
    "click_drag": "समस्या हायलाइट करण्यासाठी क्लिक आणि ड्रॅग करा",
    "enter_location": "रस्ता/क्षेत्राचे नाव प्रविष्ट करा...",
    "reset": "रीसेट",
    "analyze": "विश्लेषण करा",
    "confirm_location": "स्थान पुष्टी करा",
    "inspection_status": "तपासणी स्थिती",
    "report_ref": "अहवाल संदर्भ #",
    "tab_overview": "आढावा",
    "tab_analysis": "विश्लेषण",
    "tab_action": "कृती",
    "issue_identified": "ओळखलेली समस्या",
    "location_details": "स्थान तपशील",
    "view_maps": "गुगल मॅप्सवर पहा",
    "ai_cross_reference": "एआय क्रॉस-रेफरन्स",
    "proceed_action": "कृतीकडे जा",
    "data_insights": "डेटा अंतर्दृष्टी",
    "leading_cause": "मुख्य कारण",
    "time_analysis": "वेळ विश्लेषण",
    "high_risk_zones": "उच्च जोखीम क्षेत्रे",
    "generate_complaint": "अधिकृत तक्रार तयार करा",
    "draft_instruction": "संबंधित नगरपालिका अधिकाऱ्याला औपचारिक पत्र तयार करा.",
    "draft_button": "पत्र तयार करा",
    "drafting": "मसुदा तयार होत आहे...",
    "letter_preview": "पत्र पूर्वावलोकन",
    "copy_text": "मजकूर कॉपी करा",
    "send_complaint": "तक्रार पाठवा",
    "processing": "डेटा प्रक्रिया",
    "processing_desc": "सिस्टम पायाभूत सुविधांच्या स्थितीचे विश्लेषण करत आहे...",
    "select_coordinates": "निर्देशांक निवडा",
    "search_address": "पत्ता शोधा...",
    "locating": "शोधत आहे...",
    "my_location": "माझे स्थान",
    "surveillance": "निगरानी",
    "geo_tagging": "जिओ टॅगिंग",
    "evidence_record": "पुरावा रेकॉर्ड",
    "location_coordinates": "स्थान निर्देशांक",
    "new_audit": "नवीन ऑडिट",
    "try_again": "पुन्हा प्रयत्न करा",
    "processing_error": "प्रक्रिया त्रुटी",
    "day": "दिवस",
    "night": "रात्र",
    "select_email": "ईमेल ॲप निवडा",
    "choose_send_method": "तुम्हाला हा अहवाल कसा पाठवायचा आहे ते निवडा",
    "use_default_app": "डीफॉल्ट ॲप वापरा",
    "copied": "कॉपी केले",
    "report_ready": "अहवाल तयार",
    "report_failed": "अहवाल निर्मिती अयशस्वी",
    "unknown_location": "अज्ञात स्थान",
    "tour_welcome_title": "RoadGuard मध्ये आपले स्वागत आहे",
    "tour_welcome_desc": "सुरक्षित भारतीय रस्त्यांसाठी तुमचा एआय-सक्षम सहाय्यक. हे कसे कार्य करते ते पाहण्यासाठी एक द्रुत टूर करूया.",
    "tour_start": "टूर सुरू करा",
    "tour_skip": "वगळा",
    "tour_next": "पुढील",
    "tour_finish": "सुरू करा",
    "tour_lang_title": "भाषा निवडा",
    "tour_lang_desc": "तुम्ही तुमची पसंतीची भाषा येथे कधीही बदलू शकता.",
    "tour_logs_title": "क्रियाकलाप लॉग",
    "tour_logs_desc": "तुमच्या मागील क्रिया, विश्लेषण इतिहास आणि सिस्टम स्थिती लॉग येथे पहा.",
    "tour_upload_title": "पुरावा अपलोड करा",
    "tour_upload_desc": "रस्त्यावरील धोक्याचा (खड्डे, तुटलेले दिवे इ.) फोटो अपलोड करून ऑडिट सुरू करा.",
    "help_tour": "टूर पुन्हा प्ले करा",
    "continue": "सुरू ठेवा",
    "select_language_first": "तुमची भाषा निवडा"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const storedLang = localStorage.getItem('roadguard_language') as Language;
    if (storedLang && translations[storedLang]) {
      setLanguage(storedLang);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('roadguard_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
